version: "3"

services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: db
    env_file:
      - ./.env
    expose:
      - 5432

  django:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    command: bash -c "python /code/manage.py migrate --noinput &&
             python /code/manage.py loaddata survey/fixtures/default.json &&
             python /code/manage.py collectstatic --noinput &&
             python /code/manage.py createsuperuser --noinput &&
             gunicorn nomia.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    env_file:
      - ./.env
    expose:
      - 8000
    depends_on:
      - db
    ports:
      - 8000:8000
  
volumes:
  db_data:
  static_volume:
  media_volume:
