# Generated by Django 5.0.2 on 2024-02-11 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='Test')),
            ],
            options={
                'verbose_name': 'Опросы',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='TypeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVerificationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_verification', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='Опрос')),
                ('type_answer', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.typequestion', verbose_name='Тип ответа')),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='VerificationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.typequestion', verbose_name='Тип вопроса')),
                ('type_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.typeverificationanswer', verbose_name='Тип сопоставления')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Ответ')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='survey.question', verbose_name='Следующий вопрос')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.question', verbose_name='Вопрос')),
                ('verify', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.verificationanswer', verbose_name='Тип сопоставления')),
            ],
            options={
                'verbose_name': 'Ответы',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
