# Generated by Django 5.0.2 on 2024-02-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_useranswer_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='session',
            field=models.CharField(max_length=200),
        ),
    ]
